---
services: docker

# Use the new container infrastructure
sudo: yes

env:
  - init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    WEB_ROOT_DIR: /var/www/html
  # - distro: centos7
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   playbook: centos-7-test.yml

services:
  - docker

before_install:
  - docker pull williamyeh/ansible:ubuntu16.04
  #- 'docker pull registry.access.redhat.com/rhel7.3'

script: >
  
  container_id=$(mktemp)

  #docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} registry.access.redhat.com/rhel7.3 "${init}" > "${container_id}"

  docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} -e "ANSIBLE_HASH_BEHAVIOUR=merge" williamyeh/ansible:ubuntu16.04 "${init}" > "${container_id}"

  #docker exec --tty $(cat ${container_id}) subscription-manager register --username="${RHN_USERNAME}" --password="${RHN_PASSWORD}"

  #docker exec --tty $(cat ${container_id}) bash /etc/ansible/roles/role_under_test/tests/prep_env.sh

  docker exec --tty $(cat ${container_id}) env

  docker exec --tty $(cat ${container_id}) find /etc/ansible/roles -maxdepth 2

  docker exec --tty $(cat ${container_id}) ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} -i /etc/ansible/roles/role_under_test/tests/inventory --syntax-check

  docker exec --tty $(cat ${container_id}) ansible-playbook -i /etc/ansible/roles/role_under_test/tests/inventory /etc/ansible/roles/role_under_test/tests/${playbook} --extra-vars '{ \"redhat_localrepo\": { \"rhn_username\": \"${RHN_USERNAME}\", \"rhn_password\": \"${RHN_PASSWORD}\" }}' --tags "debug" --connection=local --sudo

  #- docker exec --tty $(cat ${container_id}) du -h -d 1 ${WEB_ROOT_DIR}
  

notifications:
  webhooks: 
    - https://galaxy.ansible.com/api/v1/notifications/
    - https://outlook.office.com/webhook/36824a68-81b0-42e7-a25f-26c2b8bf368e@438d6edb-19d9-48d4-84fe-7737135902d5/TravisCI/948ec3fe9fac4fd9a8941121966a13ca/ee481e59-19dc-48d5-9d40-144b1a6cd74a